# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
    laravel:
        build: .
        image: registry.gitlab.com/osoobe/chanceja/neura
        env_file: ./.env_file
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmariadb:
        driver: local
